# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KSYPlayerUIDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  #默认使用静态直播库
  #pod 'KSYMediaPlayer_iOS',                              :path => '../'
  
  #使用静态直播库
  pod 'KSYMediaPlayer_iOS/KSYMediaPlayer_live',         :path => '../'
  
  #使用动态直播库
  #pod 'KSYMediaPlayer_iOS/KSYMediaPlayer_live_dy',      :path => '../'
  
  #使用静态点播库
  #pod 'KSYMediaPlayer_iOS/KSYMediaPlayer_vod',          :path => '../'
  
  #使用动态点播库
  #pod 'KSYMediaPlayer_iOS/KSYMediaPlayer_vod_dy',       :path => '../'
  pod 'SDWebImage'
  pod 'JSONModel'
  pod 'Masonry'
  pod 'Toast'
  pod 'Bugly'
  # Pods for MediaPlayerUIDemo

end
